# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: outline-secret
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: /default/outline/secret-key
  - secretKey: UTILS_SECRET
    remoteRef:
      key: /default/outline/utils-secret
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: /default/outline/oidc-client-secret
