---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/cnpg-backup
- ../../../components/kopiur
resources:
- helmrelease.yaml
- oidcclient.yaml
- postgres-cluster.yaml
- externalsecret.yaml
