[env]
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
DIFFTOOL = "delta"
FLATE_PATH = "{{config_root}}/kubernetes/flux/cluster"

[tools]
crane = "latest"
delta = "latest"
flux2 = "2.9.1"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
gum = "latest"
helm = "4.2.2"
helmfile = "latest"
infisical = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kubectl = "1.36.2"
"npm:@doist/outline-cli" = "latest"
kustomize = "latest"
markdownlint-cli2 = "latest"
"github:mitsuhiko/minijinja" = "latest"
pre-commit = "latest"
python = "3.14"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
talosctl = "1.13.5"
"github:simulot/immich-go" = "latest"
"github:home-operations/flate" = "latest"
"github:hyperb1iss/unifly" = "latest"
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"
"npm:@stephendolan/ynab-cli" = "latest"

[hooks.enter]
shell = "zsh"
script = "eval \"$(just --completions bash)\""
