---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./externalsecret.yaml
- ./helmrelease.yaml
configMapGenerator:
- name: plexanisync-config
  files:
  - custom_mappings.yaml=./config/custom_mappings.yaml
generatorOptions:
  disableNameSuffixHash: true
