---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/opentelemetry.io/instrumentation_v1alpha1.json
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: home-ops
spec:
  exporter:
    endpoint: http://otel-gateway-collector.observability:4318
  propagators: [tracecontext, baggage]
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-gateway-collector.observability:4318
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
      value: "true"
    - name: OTEL_PYTHON_LOG_CORRELATION
      value: "true"
