# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-repository-secret
    creationPolicy: Owner
  data:
  - secretKey: KOPIA_PASSWORD
    remoteRef:
      key: /storage/kopiur/repository-password
