---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kometa-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Plex configuration
        KOMETA_PLEXTOKEN: "{{ .plex_token }}"
        # TMDB configuration
        KOMETA_TMDBAPIKEY: "{{ .tmdb_api_key }}"
        # MDBList configuration
        KOMETA_MDBLISTAPIKEY: "{{ .mdblist_api_key }}"
  data:
  - secretKey: plex_token
    remoteRef:
      key: /media/kometa/plex-token
  - secretKey: tmdb_api_key
    remoteRef:
      key: /media/kometa/tmdb-api-key
  - secretKey: mdblist_api_key
    remoteRef:
      key: /media/kometa/mdblist-api-key
