# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- helmrelease.yaml
- pvc.yaml
- externalsecret.yaml
configMapGenerator:
- name: docs-mcp-server-config
  files:
  - config.yaml=./config/config.yaml
  - refresh-all.mjs=./config/refresh-all.mjs
generatorOptions:
  disableNameSuffixHash: true
