---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs-single
spec:
  targetNamespace: observability
  interval: 10m
  timeout: 20m
  path: ./kubernetes/apps/observability/victoria-logs-single
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: vl
    namespace: observability
  - apiVersion: v1
    kind: Service
    name: vl
    namespace: observability
  dependsOn:
  - name: global-config
    namespace: flux-system
  - name: victoria-metrics-k8s-stack
    namespace: observability
