---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./vlsingle.yaml
- ./vmalert.yaml
- ./log-volume-alerts.yaml
- ./httproute.yaml
