---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-scrape
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-scrape
rules:
- apiGroups: [""]
  resources:
  - endpoints
  - namespaces
  - nodes
  - nodes/metrics
  - nodes/proxy
  - pods
  - services
  verbs: [get, list, watch]
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [get, list, watch]
- apiGroups: [monitoring.coreos.com]
  resources: [podmonitors, probes, scrapeconfigs, servicemonitors]
  verbs: [get, list, watch]
- nonResourceURLs: [/metrics]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-scrape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-scrape
subjects:
- kind: ServiceAccount
  name: otel-scrape
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-scrape-secrets
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-scrape-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-scrape-secrets
subjects:
- kind: ServiceAccount
  name: otel-scrape
  namespace: observability
