# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: searxng-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Injected into settings.yml by init container
        SECRET_KEY: "{{ .secret_key }}"
        BRAVE_API_KEY: "{{ .brave_api_key }}"
        WOLFRAM_API_KEY: "{{ .wolfram_api_key }}"
        REDDIT_CLIENT_ID: "{{ .reddit_client_id }}"
  data:
  - secretKey: secret_key
    remoteRef:
      key: /default/searxng/secret-key
  - secretKey: brave_api_key
    remoteRef:
      key: /default/searxng/brave-api-key
  - secretKey: wolfram_api_key
    remoteRef:
      key: /default/searxng/wolfram-api-key
  - secretKey: reddit_client_id
    remoteRef:
      key: /default/searxng/reddit-client-id
