# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ngx-secret
    creationPolicy: Owner
  data:
  - secretKey: PAPERLESS_SECRET_KEY
    remoteRef:
      key: /default/paperless-ngx/secret-key
  - secretKey: PAPERLESS_ADMIN_USER
    remoteRef:
      key: /default/paperless-ngx/admin-username
  - secretKey: PAPERLESS_ADMIN_PASSWORD
    remoteRef:
      key: /default/paperless-ngx/admin-password
