---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
