---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
spec:
  namespaceSelector:
    matchNames:
    - flux-system
  selector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - kustomize-controller
      - helm-controller
      - source-controller
      - notification-controller
  podMetricsEndpoints:
  - port: http-prom
    scheme: http
    path: /metrics
