---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- ./helmrelease.yaml
- ./postgres-cluster.yaml
- ./postgres-scheduled-backup.yaml
- ./pvc.yaml
- ./s3.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: garage-s3-region
  literals:
  - AWS_REGION=garage
