---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
labels:
- pairs:
    observability.home-ops/datasource: metrics
resources:
- ./backup-alerts.yaml
- ./certificate-alerts.yaml
- ./cluster-health.yaml
- ./kubernetes-alerts.yaml
- ./observability-alerts.yaml
- ./telemetry-storage-alerts.yaml
- ./ceph-alerts.yaml
- ./pvc-alerts.yaml
- ./unifi-alerts.yaml
