---
# yaml-language-server: $schema=https://raw.githubusercontent.com/victoriametrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmrules.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: pvc-alerts
spec:
  groups:
  - name: persistent-volume-capacity
    interval: 30s
    rules:
    - alert: PVCNearCapacity
      expr: |
        100 * otel:pvc_usage:ratio{
          k8s_persistentvolumeclaim_name!~"volsync-src-.*-cache"
        } > 85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: >-
          PVC {{ $labels.k8s_namespace_name }}/{{ $labels.k8s_persistentvolumeclaim_name }}
          is nearing capacity
        description: The claim is {{ printf "%.1f" $value }}% full

    - alert: PVCCriticalCapacity
      expr: |
        100 * otel:pvc_usage:ratio{
          k8s_persistentvolumeclaim_name!~"volsync-src-.*-cache"
        } > 95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: >-
          PVC {{ $labels.k8s_namespace_name }}/{{ $labels.k8s_persistentvolumeclaim_name }}
          is critically full
        description: The claim is {{ printf "%.1f" $value }}% full
