---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: VictoriaMetrics
    uid: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm.observability:8428
    isDefault: true
    jsonData:
      prometheusType: Prometheus
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: VictoriaLogs
    uid: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vl.observability:9428
    jsonData:
      maxLines: 1000
      derivedFields:
      - name: Trace
        matcherRegex: 'trace_id[=:]"?([a-f0-9]{32})'
        datasourceUid: VictoriaTraces
        url: '$${__value.raw}'
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriatraces
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: VictoriaTraces
    uid: VictoriaTraces
    type: tempo
    access: proxy
    url: http://vt.observability:10428/select/tempo
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      streamingEnabled:
        search: false
        metrics: false
      tracesToLogsV2:
        datasourceUid: VictoriaLogs
        filterByTraceID: true
        filterBySpanID: true
        tags:
        - key: service.name
          value: service.name
        - key: k8s.namespace.name
          value: k8s.namespace.name
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: vmalertmanager
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: VMAlertmanager
    uid: VMAlertmanager
    type: alertmanager
    access: proxy
    url: http://vmalertmanager-vm.observability:9093
    jsonData:
      implementation: prometheus
