---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- ./externalsecret.yaml
- ./httproute.yaml
- ./grafana.yaml
- ./grafanadatasource.yaml
- ./dashboards/grafanadashboard.yaml
configMapGenerator:
- name: otel-kubernetes-dashboard
  files:
  - otel-kubernetes.json=dashboards/otel-kubernetes.json
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/managed-by: grafana-operator
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
- name: etcd-dashboard
  files:
  - etcd.json=dashboards/etcd.json
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/managed-by: grafana-operator
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
