# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ./s3.yaml
- ./objectstore.yaml
- ./postgres-scheduled-backup.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: garage-s3-region
  literals:
  - AWS_REGION=garage
patches:
- target:
    group: postgresql.cnpg.io
    version: v1
    kind: Cluster
    name: .*\-postgres
  patch: |-
    - op: add
      path: /spec/backup
      value:
        target: "prefer-standby"
    - op: add
      path: /spec/plugins
      value:
      - name: barman-cloud.cloudnative-pg.io
        isWALArchiver: true
        parameters:
          barmanObjectName: ${APP}-postgres-backups
