---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/nfs-scaler
- ../../../components/otel-collector-baseline
- ../../../components/volsync
resources:
- ./collector.yaml
- ./helmrelease.yaml
- ./logrule.yaml
- ./pvc.yaml
- ./resourceclaimtemplate.yaml
- ./loadbalancer-service.yaml
