---
provider: inmemory
extraArgs:
- --inmemory-zone=${SECRET_DOMAIN}
triggerLoopOnEvent: true
policy: sync
txtPrefix: k8s.
txtOwnerId: dns-private
domainFilters: ["${SECRET_DOMAIN}"]
serviceMonitor:
  enabled: true
podAnnotations:
  reloader.stakater.com/auto: "true"
